products_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from apps.products.api.viewsets import ProductViewSet, CategoryListViewSet, ProductDetailViewSet
from apps.accounts.api.viewsets import UserViewSet, UserListViewSet, ProfileUserViewSet
from apps.vendor.api.viewsets import VendorViewSet, VendorValueViewSet

version_api = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vendor.urls')),
    path('', include('products.urls')),
    path('', include('accounts.urls')),
    path('', include('core.urls')),
] 

class GestaoDeFornecedores(routers.APIRootView):
    """
    Api para gerenciar fornecedores, e listar os melhores preços
    """
    pass

class DocumentedRouter(routers.DefaultRouter):
    APIRootView = GestaoDeFornecedores

router = DocumentedRouter()

router.register(r'user', UserViewSet, basename='Usuário')
router.register(r'users', UserListViewSet, basename='Usuários')
router.register(r'user-profile', ProfileUserViewSet, basename='Perfil do usuário')
router.register(r'products', ProductViewSet, basename='Produtos')
router.register(r'category', CategoryListViewSet, basename='Categorias')
router.register(r'vendor', VendorViewSet, basename='Fornecedores')
router.register(r'vendor-product-value', VendorValueViewSet, basename='Registar preço produtos')


urlpatterns += [
    path(version_api, include(router.urls)),
    path(f'{version_api}products/<int:product_id>', ProductDetailViewSet.as_view()),
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models/product_model.py
from django.db import models
from PIL import Image

from products.models.category_model import Category


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    product_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    image_product = models.ImageField(upload_to='product', blank=True, null=True)
    is_available = models.BooleanField(verbose_name='Produto ativo', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_title

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'


templates/includes/alerts.html

{% if messages %}
    {% for message in messages %}
    <div id="message_alert" aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-absolute top-0 end-0 p-3">
            <div class="toast col-md-12 alert alert-{{message.tags}} text-white bg-{{message.tags}} alert-dismissible fade show"  role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
                <strong>{{message}}</strong>
            </div>
        </div>
    </div>

    <script>
        $(function() {
            if ($('#message_alert').length) {
                setTimeout(() => {
                    $('#message_alert').hide('slideUp')
                    setTimeout(() => {
                        $('#message_alert').remove()
                    }, 500)
                }, 3500)
            }
        })
    </script>

    {% endfor %}

{% endif %}



templates/includes/footer.html
{% load static %}

<!-- footer section start -->
<div class="footer_section layout_padding">
    <div class="container">
       <div class="footer_logo"><a href="{% url 'home' %}"><h2 class="banner_taital">TK GLobal</h2></a></div>
       <div class="input_bt">
          <input type="text" class="mail_bt" placeholder="Seu E-mail" name="email">
          <span class="subscribe_bt" id="basic-addon2"><a href="#">SE INSCREVER</a></span>
       </div>
       <div class="footer_menu">
          <ul>
             <li><a href="#">Mais produrados</a></li>
             <li><a href="#">Ideias de presentes</a></li>
             <li><a href="#">Novos Fornecedores</a></li>
             <li><a href="#">Menor preço</a></li>
             <li><a href="#">Atendimento ao Cliente</a></li>
          </ul>
       </div>
       <div class="location_main">Número de contato : <a href="#">+55 (74) 98119-9190</a></div>
    </div>
 </div>
 <!-- footer section end -->

templates/includes/header.html
{% load static %}

{% load widget_tweaks %}

<!-- logo section start -->
<div class="logo_section">
   <div class="container">
      <div class="row">
         <div class="col-sm-12">
            <div class="logo"><a href="{% url 'home' %}"><h2 class="banner_taital">TK GLobal</h2></a></div>
         </div>
      </div>
   </div>
</div>
<!-- logo section end -->

<!-- header section start -->
<div class="header_section">
   <div class="container">
      <div class="containt_main  mb-3">
         <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'product_list' %}">Produtos</a>
            <a href="{% url 'registerVendor' %}">Novo Fornecedor</a>
            <a href="{% url 'registerUser' %}">Novo usuário</a>
            {% if request.user.is_authenticated %}
               <a href="#" data-bs-toggle="modal" data-bs-target="#modal-category">Nova categoria</a>
               <a href="#" data-bs-toggle="modal" data-bs-target="#modal-product">Novo Produto</a>
               <a href="{% url 'myAccount' %}">Perfil</a>
               <a href="{% url 'logout' %}">Sair</a>
            {% else %}
               <a href="{% url 'login' %}">Login</a>
            {% endif %}
            <a href="{{domain}}/api/v1">Api</a>

         </div>
         <span class="toggle_icon" onclick="openNav()"><img src="{% static 'images/toggle-icon.png' %}"></span>
         
         {% if request.path == '/menu-builder/products/' %}
            <div class="main">
               <form action="" method="get" class="row"> {% csrf_token %}
                     <div class="col-sm-3 col-md-3">
                        <div class="input-group">
                           <div class="input-group-append">
                              {% render_field product_filter.form.category class="form-control col-md-12" %}
                              <button class="btn btn-secondary" type="submit" style="background-color: #f26522; border-color:#f26522 ">
                                    <i class="fa fa-search"></i>
                              </button>
                           </div>
                        </div>
                     </div>
                  <div class="col-sm">
                        <div class="input-group">
                           {{ product_filter.form.product_title }}
                           <div class="input-group-append">
                              <button class="btn btn-secondary" type="submit" style="background-color: #f26522; border-color:#f26522 ">
                                    <i class="fa fa-search"></i>
                              </button>
                           </div>
                        </div>
                     </div>
               </form>
            </div>
         {% endif %}

         <div class="header_box">
            <div class="lang_box ml-4">
               <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
               <img src="{% static 'images/brasil.png' %}" alt="flag" class="mr-1" width="20px" title="portuguese Kingdom"> Português <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
               </a>
               <div class="dropdown-menu ">
                  <a href="#" class="dropdown-item">
                  <img src="{% static 'images/flag-uk.png' %}" class="mr-1" alt="flag">
                  Inglês
                  </a>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- header section end -->
   {% if request.path != '/perfil/'%}
   <!-- banner section start -->
   <div class="banner_section layout_padding">
      <div class="container">
         <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="row">
                     <div class="col-sm-12">
                        <h1 class="banner_taital">Os produtos <br>mais buscados no mercado</h1>
                        <div class="buynow_bt"><a href="#">Contatar</a></div>
                     </div>
                  </div>
               </div>
               
               <div class="carousel-item">
                  <div class="row">
                     <div class="col-sm-12">
                        <h1 class="banner_taital">Fornecedores <br>com melhores preços</h1>
                        <div class="buynow_bt"><a href="#">Contatar</a></div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
   </div>
   {% endif %}
   <!-- banner section end -->
</div>


<!-- banner bg main end -->

templates/includes/navbar.html

<!-- header top section start -->
<div class="container">
   <div class="header_section_top">
      <div class="row">
         <div class="col-sm-12">
            <div class="custom_menu">
               <ul>
               <li><a href="{% url 'home' %}">Home</a></li>
               <li><a href="{% url 'product_list' %}">Produtos</a></li>
               <li><a href="{% url 'registerVendor' %}">Novo Fornecedor</a></li>
               <li><a href="{% url 'registerUser' %}">Novo usuário</a></li>
            {% if request.user.is_authenticated %}
               <li><a href="{% url 'myAccount' %}">Perfil</a></li>
            {% endif %}
               <li><a href="{{domain}}/api/v1">Api</a></li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</div>

templates/includes/scripts-head.html
{% load static %}

<!-- bootstrap css -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<!-- style css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<!-- Responsive-->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<!-- fevicon -->
<link rel="icon" href="{% static 'images/banner-bg.png' %}" type="image/gif" />
<!-- Scrollbar Custom CSS -->
<link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
<!-- Tweaks for older IEs-->
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<!-- fonts -->
<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
<!-- font awesome -->
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!--  -->
<!-- owl stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesoeet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >

<!-- FORME INLINE -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'js/inline_form/jquery.formset.js' %}"></script>
<script src="{% static 'js/inline_form/jquery-ui.js' %}"></script>

templates/includes/scripts-js.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="{% static 'js/plugin.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>

<!-- sidebar -->
<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script>
    function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    }
    
    function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    }
</script>


<!-- Scripts: Bootstraps, HTMX, and custom JavaScript -->
<script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
{#<script src="{% static 'js/dialog.js' %}"></script>#}
<script src="{% static 'js/toast.js' %}"></script>